# Generated by Django 4.2.5 on 2023-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0011_alter_membership_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/instructors'),
        ),
    ]
