# Generated by Django 4.2.5 on 2023-09-14 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0012_alter_instructor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number should be in the format: +375(xx)xxx-xx-xx', regex='^\\+375\\(\\d{2}\\)\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Phone number'),
        ),
    ]
