# Generated by Django 4.2.5 on 2023-09-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0015_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/news'),
        ),
    ]
