# Generated by Django 4.2.5 on 2023-09-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0017_rename_new_news_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
            },
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocation', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Vocation',
                'verbose_name_plural': 'Vocations',
            },
        ),
    ]
