# Generated by Django 4.2.5 on 2023-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0018_dictionary_vocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=100, null='True', verbose_name='Last name'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, null='True', verbose_name='First name'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='feedback',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null='True', verbose_name='Creation time'),
            preserve_default='True',
        ),
    ]
