# Generated by Django 4.2.5 on 2023-09-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0020_faq_delete_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
