# Generated by Django 4.2.5 on 2023-09-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0021_alter_faq_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='read_more_link',
            field=models.URLField(null=True),
        ),
    ]
