# Generated by Django 4.2.5 on 2023-09-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_club', '0022_news_read_more_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='read_more_link',
        ),
    ]
